{% set name = "tokenize-rt" %}
{% set version = "2.1.0" %}
{% set hash = "c218980dd483c407aa89683c9dfcee7935fc5efd05e8255a3eabfd8c81bcd437" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - tokenize_rt

about:
  home: https://github.com/asottile/tokenize-rt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary:
    A wrapper around the stdlib `tokenize` which roundtrips.

extra:
  recipe-maintainers:
    - sterlingbaldwin
    - deadsnakes-issues-bot
    - nicoddemus
