{% set name = "tokenize-rt" %}
{% set version = "3.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tokenize_rt-{{ version }}.tar.gz
  sha256: "2f44eee8f620102f8a03c50142795121faf86e020d208896ea7a7047bbe933cf"

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - tokenize-rt = tokenize_rt:main

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - tokenize_rt
  commands:
    - tokenize-rt --help

about:
  home: https://github.com/asottile/tokenize-rt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary:
    A wrapper around the stdlib `tokenize` which roundtrips.

extra:
  recipe-maintainers:
    - sterlingbaldwin
    - deadsnakes-issues-bot
    - nicoddemus
