travis:
  secure:
    BINSTAR_TOKEN: hZ1T7e3diwvCe1x+4oaXg2ojWopjcGhXPcPXaCEu9loTSn92c4bBm0AlZQCJtCUYITEoBALm086nYFgwi3LOIVd4amJ7R+gFmVMRYQJUrplHGr+5yl5agvJ9GmHzDM5mEgpMOpMtO1LJ9pvZkc8wnZKkfpV8A0JAuQWp27k1RffHfuJsYIECDsmd1fByfN5K60hsUo7RZxLp3PTrafNRQm19YxJv1XmULVUeHf3r5ViNomWPkUriHCcfLFYzaU6bpkXYKYcJ51AmJUUZkLjIMrW2o07Lygg23gbpANhoR8uCQPlbQkCzo/XZIkS6cAK6TgcR6b1NqkchHrNBajDiE4HMwae94QUwUHh33oD2y8k9hnW+wqqqyfJnaNGLFF3ShYFHjAC6sfwP2pWOL/FPIOGMOAkPdqV7lrp0wQKPh+7GkS80+DiVEE8oR+f7xPWK2VKKQ1cKbnx6q/mu7aMpBVh5uH8nMZM9hzaFrt9cpPx7s246eQicUlHG6GzB9q88CKA+pckB3O0mqD5Rmx8OLUI9WLYlCR4KTDq1PUaRPjBuNlg8lqwgrsl5Z5l6ozbeDLf5nTULjnqhXE8SMTUmSYKqcBccYrhbmS9NoItSILKQwIV8BZ1nkDAeQsKdKAHCq9NuPorFiWukw22LrMbZ+Z8C5FufhHuaCNXnwXsr7eA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
