travis:
  secure:
    BINSTAR_TOKEN: dgIxYnPpzvETBwp0NG22zpPBriGUnh+kLC966IQMwsrIsGCEp/IsmLixtohS37mAbLuEpToMdxdNDajLJUjr16lfElzMs2fdiqB9zAqEOFpoe5PIk4+MbK+QSjtQSM53kqvyOHo5KZlFuoJP3mkuk2VjtX5+X/tG90ZCeguQ7v9fS9vS79BcaY5TudZvZ8wN/y4uDxpH5tIXMRLEkMctrjTaz5Ck9fE2oW0iGnQAkKKMBLTR/37KHtqMk2TIwovMOBzHAt3JNa3X1LZEYZ9Dx2UV1Og/iJI8khsRWgNW/ftUugGulCjpIpaBfTGYi3HdTM4gngSDwwDHARUkSYBEbuJKKn4XdRaHl3SzS8aAhS0BC/TkO+0JCxS4rwTa/eyRgExyxA6q5UBHrYyqu3COCM9wfNv7fkD8iq4KS6c1T7hPZsavBDZ/F/QNjvNqK/5HGDLiOqso5Gwt0uuS4DjfJaUOXEmIn9Jtg/Gz7fEeNR+IgUJnUXYnVONu4Lm48BQSj2r4+s+QL4uflbYQhzfBGypLC5/B8aMJMGW4yJiGwMNmE3us1E7/d4j17fj05sMmo7DgQHijPI82AgNsaWI/KkyhXeUWt4fHWdPBGwy/Zgg/CHLBTgXibD7L0ZK/q+EsK+Z4XLIFLxf9y47ghBcPLkyEEioi+Z4WAOixboJoWA0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
